### ISSUE TITLE
An understanding of TableTransform

### ISSUE THREAD

**Issue by zeus527** [rllm-team/rllm#145]
In my opinion, GraphTransform is relatively easy to understand, mainly doing transformation operations on the graph, such as adding self-loop and Laplace normalization of the graph. But what is the main job of TableTransform? What does his location have to do with GraphTransform?

**Comment by zeus527** [comment]
Thank you for your reply. Is there any basis for these definitions or strategies? I don't think I've seen that in any papers so far.

**Comment by JianwuZheng413** [comment]
You are right. Our definition of TableTransform is based on several well-known GNN and TNN libraries. On the basis of their summary and refinement, the definition and function of the current TableTransform are determined. We believe that the current definition can uniformly describe the role of Transform in TNN and GNN. Of course, this pattern can also avoid some of the repetitive work in the model training.

**Comment by JianwuZheng413** [comment]
Of course. You can implement your own operating modules or use the modules we have integrated according to your own needs. Implement a new class you need by inheriting the TableTransform class. This new Transform performs the operation of your choice.

**Comment by zeus527** [comment]
I see. Thank you for your answer.
