### ISSUE TITLE
TACM12K dataset preprocessing

### ISSUE THREAD

**Issue by zeus527** [rllm-team/rllm#52]
How can I to obtain the embeddings of paper and author in the TACM12K dataset. The code is not found in the rllm.

**Comment by Mr-Zhengjw** [comment]
For simplicity, the embeddings in the dataset were obtained using all-MiniLM-L6-v2. The embedding of the model is 384 dimensions. This model we only carried out a simple processing, there are still some imperfections. A more reasonable approach will follow. If the embeddings in the data set do not meet the requirements, you can perform your own embeddings as needed. Welcome to communicate.

**Comment by zeus527** [comment]
Issue was fixed. Thanks for the assistance
