### ISSUE TITLE
`post_filter` in `label_free_gnn` example is Time-Consuming Due to Redundant Computations

### ISSUE THREAD

**Issue by Nonsense213** [rllm-team/rllm#54]
**Describe your question**
I've noticed that the entropy calculation in the `post_filter` function is significantly time-consuming.  It appears that this is due to redundant computations in the sorting process, which introduces unnecessary time cost. It should be optimized to avoid unnecessary computational overhead.

**Describe the solution you'd like to know**
Opmized the redundant computations to avoid unnecessary computational overhead.

**Comment by W1nterFloW** [comment]
Thank you for reporting this! We've optimized the post_filter function to remove the redundant computations. This should now be much faster. Please update to the latest version to get this fix!
