### ISSUE TITLE
Requested tokens exceed context window

### ISSUE THREAD

**Issue by Nonsense213** [rllm-team/rllm#55]
**Describe your question**
I am running the label_free_gnn example and occasionally encountering an error when calling a local llama.cpp model. The error message is as follows:

`ValueError: Requested tokens (516) exceed context window of 512`

It seems that the model is trying to process more tokens than the context window size allows. How do I prevent this?

**Describe the solution you'd like to know**
The model should process the tokens without exceeding the context window or handle the situation gracefully. If you need my Environment Details, please let me know!

**Comment by W1nterFloW** [comment]
This issue can be resolved by increasing the n_ctx parameter to 1024 when initializing the LlamaCpp model. Here's how you can do it:

```python
from langchain_community.llms import LlamaCpp

llm = LlamaCpp(
    model_path=model_path,
    n_ctx=1024,
    # other parameters
)
```
By setting n_ctx to 1024, the model can handle a larger context window, which should prevent the ValueError.

**Comment by Nonsense213** [comment]
Thanks very much! After taking your advice, the model is running perfectly.

**Comment by Nonsense213** [comment]
Thanks very much! After taking your advice, the model is running perfectly.
