### ISSUE TITLE
Whether the graph neural network in the BRIDGE method can be replaced by itself.

### ISSUE THREAD

**Issue by zeus527** [rllm-team/rllm#56]
The three datasets, TML1M, TLF2K and TACM12K, all have multiple edges and multiple nodes. BRIDGE code uses GCN. Can we change it to the heterogeneous graph method to get better results? For example, HAN.

**Comment by Mr-Zhengjw** [comment]
Considering that this BRIDGE method is only an instance method, the original version adopted the simplest strategy of constructing an identical graph. Of course, the method of using heterogeneous graph is also in our consideration, and the method of heterogeneous graph is also included in our library. I personally think that changing to a heterogeneous graph can really get better results. Stay tuned for future version updates.
