### ISSUE TITLE
Performance of label_free_gnn example not satisfying when using local LLMs

### ISSUE THREAD

**Issue by zeus527** [rllm-team/rllm#57]
The performance of label_free_gnn is not satisfying when using local LLMs. The LLM's output often does not conform to the required format, necessitating repeated correction. The accuracy of the results is consistently below acceptable levels, leading to poor training results.

**Comment by W1nterFloW** [comment]
Considering the limitations of local large models, I recommend switching to remote API calls from LLM services such as OpenAI or Tongyi for accessing more reliable and accurate models hosted externally. This change would likely improve processing times, output consistency, and overall accuracy.

**Comment by zeus527** [comment]
Thank you for your reply. I understand now
